// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/fiend

// This file generated by ModelGen - Do NOT Modify

#pragma once

enum {
        // stand
        FRAME_stand01,
        FRAME_stand02,
        FRAME_stand03,
        FRAME_stand04,
        FRAME_stand05,
        FRAME_stand06,
        FRAME_stand07,
        FRAME_stand08,
        FRAME_stand09,
        FRAME_stand10,
        FRAME_stand11,
        FRAME_stand12,
        FRAME_stand13,

        // walk
        FRAME_walk01,
        FRAME_walk02,
        FRAME_walk03,
        FRAME_walk04,
        FRAME_walk05,
        FRAME_walk06,
        FRAME_walk07,
        FRAME_walk08,

        // run
        FRAME_run01,
        FRAME_run02,
        FRAME_run03,
        FRAME_run04,
        FRAME_run05,
        FRAME_run06,

        // leap / pounce
        FRAME_leap01,
        FRAME_leap02,
        FRAME_leap03,
        FRAME_leap04,
        FRAME_leap05,
        FRAME_leap06,
        FRAME_leap07,
        FRAME_leap08,
        FRAME_leap09,
        FRAME_leap10,
        FRAME_leap11,
        FRAME_leap12,

        // pain
        FRAME_pain01,
        FRAME_pain02,
        FRAME_pain03,
        FRAME_pain04,
        FRAME_pain05,
        FRAME_pain06,

        // death
        FRAME_death01,
        FRAME_death02,
        FRAME_death03,
        FRAME_death04,
        FRAME_death05,
        FRAME_death06,
        FRAME_death07,
        FRAME_death08,
        FRAME_death09,

        // melee combo
        FRAME_attacka01,
        FRAME_attacka02,
        FRAME_attacka03,
        FRAME_attacka04,
        FRAME_attacka05,
        FRAME_attacka06,
        FRAME_attacka07,
        FRAME_attacka08,
        FRAME_attacka09,
        FRAME_attacka10,
        FRAME_attacka11,
        FRAME_attacka12,
        FRAME_attacka13,
        FRAME_attacka14,
        FRAME_attacka15
};

constexpr float MODEL_SCALE = 1.000000f;
