// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/ogre

// This file generated by ModelGen - Do NOT Modify

enum {
	// stand
	FRAME_stand01,
	FRAME_stand02,
	FRAME_stand03,
	FRAME_stand04,
	FRAME_stand05,
	FRAME_stand06,
	FRAME_stand07,
	FRAME_stand08,
	FRAME_stand09,
	FRAME_stand10,

	// idle / fidget
	FRAME_idle01,
	FRAME_idle02,
	FRAME_idle03,
	FRAME_idle04,
	FRAME_idle05,
	FRAME_idle06,
	FRAME_idle07,
	FRAME_idle08,

	// walk
	FRAME_walk01,
	FRAME_walk02,
	FRAME_walk03,
	FRAME_walk04,
	FRAME_walk05,
	FRAME_walk06,
	FRAME_walk07,
	FRAME_walk08,

	// run
	FRAME_run01,
	FRAME_run02,
	FRAME_run03,
	FRAME_run04,
	FRAME_run05,
	FRAME_run06,
	FRAME_run07,
	FRAME_run08,

	// melee (chainsaw)
	FRAME_melee01,
	FRAME_melee02,
	FRAME_melee03,
	FRAME_melee04,
	FRAME_melee05,
	FRAME_melee06,

	// grenade throw
	FRAME_gren01,
	FRAME_gren02,
	FRAME_gren03,
	FRAME_gren04,
	FRAME_gren05,
	FRAME_gren06,
	FRAME_gren07,
	FRAME_gren08,

	// pain sets
	FRAME_pain01,
	FRAME_pain02,
	FRAME_pain03,
	FRAME_pain04,
	FRAME_pain05,

	FRAME_painb01,
	FRAME_painb02,
	FRAME_painb03,
	FRAME_painb04,
	FRAME_painb05,
	FRAME_painb06,
	FRAME_painb07,

	// deaths
	FRAME_death01,
	FRAME_death02,
	FRAME_death03,
	FRAME_death04,
	FRAME_death05,
	FRAME_death06,
	FRAME_death07,
	FRAME_death08,

	FRAME_deathb01,
	FRAME_deathb02,
	FRAME_deathb03,
	FRAME_deathb04,
	FRAME_deathb05,
	FRAME_deathb06,
	FRAME_deathb07,
	FRAME_deathb08
};

constexpr float OGRE_MODEL_SCALE = 1.000000f;
// Alias to match other generated headers in WOR (mutant/gunner use MODEL_SCALE)
constexpr float MODEL_SCALE = OGRE_MODEL_SCALE;
