// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/spike (spike mine)

// This file generated by ModelGen - Do NOT Modify

enum {
        FRAME_spike1,
        FRAME_spike2,
        FRAME_spike3,
        FRAME_spike4,
        FRAME_spike5,
        FRAME_spike6,
        FRAME_spike7,
        FRAME_spike8,
        FRAME_spike9
};

constexpr float MODEL_SCALE = 1.000000f;
