// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/fiend

// This file generated by ModelGen - Do NOT Modify

#pragma once

enum {
	// stand
	FRAME_stand01,
	FRAME_stand02,
	FRAME_stand03,
	FRAME_stand04,
	FRAME_stand05,
	FRAME_stand06,
	FRAME_stand07,
	FRAME_stand08,
	FRAME_stand09,
	FRAME_stand10,

	// walk
	FRAME_walk01,
	FRAME_walk02,
	FRAME_walk03,
	FRAME_walk04,
	FRAME_walk05,
	FRAME_walk06,
	FRAME_walk07,
	FRAME_walk08,

	// run
	FRAME_run01,
	FRAME_run02,
	FRAME_run03,
	FRAME_run04,
	FRAME_run05,
	FRAME_run06,
	FRAME_run07,
	FRAME_run08,
	FRAME_run09,
	FRAME_run10,

	// melee claws
	FRAME_melee01,
	FRAME_melee02,
	FRAME_melee03,
	FRAME_melee04,
	FRAME_melee05,
	FRAME_melee06,

	// leap/pounce
	FRAME_leap01,
	FRAME_leap02,
	FRAME_leap03,
	FRAME_leap04,
	FRAME_leap05,
	FRAME_leap06,
        FRAME_leap07,
        FRAME_leap08,
        FRAME_leap09,
        FRAME_leap10,
        FRAME_leap11,
        FRAME_leap12,

	// pain A (short)
	FRAME_pain01,
	FRAME_pain02,
	FRAME_pain03,
	FRAME_pain04,
	FRAME_pain05,

	// pain B (long)
	FRAME_painb01,
	FRAME_painb02,
	FRAME_painb03,
	FRAME_painb04,
	FRAME_painb05,
	FRAME_painb06,
	FRAME_painb07,

	// death A
	FRAME_death01,
	FRAME_death02,
	FRAME_death03,
	FRAME_death04,
	FRAME_death05,
	FRAME_death06,
	FRAME_death07,
	FRAME_death08,
	FRAME_death09,
	FRAME_death10,

	// death B
	FRAME_deathb01,
	FRAME_deathb02,
	FRAME_deathb03,
	FRAME_deathb04,
	FRAME_deathb05,
	FRAME_deathb06,
	FRAME_deathb07,
	FRAME_deathb08,
	FRAME_deathb09,
	FRAME_deathb10,
	FRAME_deathb11,
	FRAME_deathb12
};

constexpr float MODEL_SCALE = 1.000000f;
