// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/grunt (Q1-styled)

// This file generated by ModelGen - Do NOT Modify

#pragma once

enum {
	// stand
	FRAME_stand01,
	FRAME_stand02,
	FRAME_stand03,
	FRAME_stand04,
	FRAME_stand05,
	FRAME_stand06,
	FRAME_stand07,
	FRAME_stand08,
	FRAME_stand09,
	FRAME_stand10,

	// walk
	FRAME_walk01,
	FRAME_walk02,
	FRAME_walk03,
	FRAME_walk04,
	FRAME_walk05,
	FRAME_walk06,
	FRAME_walk07,
	FRAME_walk08,

	// run
	FRAME_run01,
	FRAME_run02,
	FRAME_run03,
	FRAME_run04,
	FRAME_run05,
	FRAME_run06,

	// attack (shotgun)
	FRAME_attk01,
	FRAME_attk02,
	FRAME_attk03,
	FRAME_attk04,
	FRAME_attk05,
	FRAME_attk06,
	FRAME_attk07,
	FRAME_attk08,
	FRAME_attk09,

	// pain
	FRAME_pain01,
	FRAME_pain02,
	FRAME_pain03,
	FRAME_pain04,
	FRAME_pain05,

	// death
	FRAME_death01,
	FRAME_death02,
	FRAME_death03,
	FRAME_death04,
	FRAME_death05,
	FRAME_death06,
	FRAME_death07,
	FRAME_death08
};

constexpr float MODEL_SCALE = 1.2f;
