// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/spawn (tarbaby)

// This file generated by ModelGen - Do NOT Modify

enum {
	// idle/stand (wobble)
	FRAME_stand01,
	FRAME_stand02,
	FRAME_stand03,
	FRAME_stand04,
	FRAME_stand05,
	FRAME_stand06,
	FRAME_stand07,
	FRAME_stand08,

	// hop/walk
	FRAME_walk01,
	FRAME_walk02,
	FRAME_walk03,
	FRAME_walk04,
	FRAME_walk05,
	FRAME_walk06,
	FRAME_walk07,
	FRAME_walk08,

	// fast hop/run
	FRAME_run01,
	FRAME_run02,
	FRAME_run03,
	FRAME_run04,
	FRAME_run05,
	FRAME_run06,

	// leap (pounce)
	FRAME_leap01,
	FRAME_leap02,
	FRAME_leap03,
	FRAME_leap04,
	FRAME_leap05,
	FRAME_leap06,

	// pain
	FRAME_pain01,
	FRAME_pain02,
	FRAME_pain03,
	FRAME_pain04,

	// explode death (detonate anim, very short)
	FRAME_death01,
	FRAME_death02,
	FRAME_death03,
	FRAME_death04
};

constexpr float MODEL_SCALE = 1.000000f;
