// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// Generated from Quake model data - Do NOT Modify

enum {
	FRAME_fly1,
	FRAME_fly2,
	FRAME_fly3,
	FRAME_fly4,
	FRAME_fly5,
	FRAME_fly6,
	FRAME_fly7,
	FRAME_fly8,
	FRAME_attack1,
	FRAME_attack2,
	FRAME_attack3,
	FRAME_attack4,
	FRAME_attack5,
	FRAME_attack6,
	FRAME_attack7,
	FRAME_attack8,
	FRAME_attack9,
	FRAME_pain1,
	FRAME_pain2,
	FRAME_pain3,
	FRAME_pain4,
	FRAME_pain5,
	FRAME_pain6,
	FRAME_painb1,
	FRAME_painb2,
	FRAME_painb3,
	FRAME_painb4,
	FRAME_painb5,
	FRAME_painb6,
	FRAME_painc1,
	FRAME_painc2,
	FRAME_painc3,
	FRAME_painc4,
	FRAME_painc5,
	FRAME_painc6,
	FRAME_die1,
	FRAME_die2,
	FRAME_die3,
	FRAME_die4,
	FRAME_die5,
	FRAME_die6,
	FRAME_die7,
	FRAME_die8,
	FRAME_die9,
	FRAME_die10,
	FRAME_die11,
	FRAME_die12,
	FRAME_die13,
	FRAME_dieb1,
	FRAME_dieb2,
	FRAME_dieb3,
	FRAME_dieb4,
	FRAME_dieb5,
	FRAME_dieb6,
	FRAME_implode1,
	FRAME_implode2,
	FRAME_implode3,
	FRAME_implode4,
	FRAME_implode5,
	FRAME_implode6,
	FRAME_implode7,
	FRAME_implode8,
	FRAME_spawn1,
	FRAME_spawn2,
	FRAME_spawn3,
	FRAME_spawn4,
	FRAME_spawn5,
	FRAME_spawn6,
	FRAME_spawn7
};

constexpr float MODEL_SCALE = 1.0f;
