// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/monsters/zombie

// This file generated by ModelGen - Do NOT Modify

enum {
	// stand idle
	FRAME_stand01,
	FRAME_stand02,
	FRAME_stand03,
	FRAME_stand04,
	FRAME_stand05,
	FRAME_stand06,
	FRAME_stand07,
	FRAME_stand08,

	// shamble walk
	FRAME_walk01,
	FRAME_walk02,
	FRAME_walk03,
	FRAME_walk04,
	FRAME_walk05,
	FRAME_walk06,
	FRAME_walk07,
	FRAME_walk08,

	// run (lurch)
	FRAME_run01,
	FRAME_run02,
	FRAME_run03,
	FRAME_run04,
	FRAME_run05,
	FRAME_run06,

	// melee swipe
	FRAME_melee01,
	FRAME_melee02,
	FRAME_melee03,
	FRAME_melee04,

	// pain short
	FRAME_pain01,
	FRAME_pain02,
	FRAME_pain03,
	FRAME_pain04,

	// death fall (feign)
	FRAME_death01,
	FRAME_death02,
	FRAME_death03,
	FRAME_death04,
	FRAME_death05,
	FRAME_death06,

	// getup (resurrect)
	FRAME_getup01,
	FRAME_getup02,
	FRAME_getup03,
	FRAME_getup04,
	FRAME_getup05,
	FRAME_getup06,
	FRAME_getup07,
	FRAME_getup08
};

constexpr float MODEL_SCALE = 1.000000f;
