// version.hpp (Shared Version Information)
// Centralized definitions for the WORR title and dynamically generated build
// version. The version string may be injected by the build system so that
// runtime commands (for example the `gameversion` console command) and logs
// report the exact build that produced the binary.

#pragma once

#include <string_view>

namespace worr::version {

// Human-friendly name for the mod. Shared between the client and the server so
// text shown to the user remains consistent across modules.
inline constexpr std::string_view kGameTitle{"WORR"};

namespace detail {

#if defined(WORR_GENERATED_VERSION_STRING)
inline constexpr std::string_view kVersionSource{WORR_GENERATED_VERSION_STRING};
#elif defined(WORR_GENERATED_VERSION)
inline constexpr std::string_view kVersionSource{WORR_GENERATED_VERSION};
#elif defined(WORR_VERSION_STRING)
inline constexpr std::string_view kVersionSource{WORR_VERSION_STRING};
#elif defined(WORR_VERSION)
inline constexpr std::string_view kVersionSource{WORR_VERSION};
#else
// Fallback used when the build system has not injected a version yet. This
// keeps local development builds compiling while still providing a sensible
// default value.
inline constexpr std::string_view kVersionSource{"0.60.10 BETA dev"};
#endif

}  // namespace detail

// Full display version for the running build. Downstream code should rely on
// this constant so that version reporting is consistent everywhere.
inline constexpr std::string_view kGameVersion = detail::kVersionSource;

#pragma once

// This file is auto-generated by tools/release/bump_version.py. Do not edit manually.

namespace worr::version {
inline constexpr int kMajor = 0;
inline constexpr int kMinor = 1;
inline constexpr int kPatch = 0;
inline constexpr bool kHasPrerelease = false;
inline constexpr bool kHasBuildMetadata = false;
inline constexpr const char* kPrerelease = "";
inline constexpr const char* kBuildMetadata = "";
inline constexpr const char* kVersion = "0.1.0";
}  // namespace worr::version

// This file is generated. Do not edit directly.
#pragma once

#define WORR_VERSION_MAJOR 0
#define WORR_VERSION_MINOR 1
#define WORR_VERSION_PATCH 0
#define WORR_VERSION_PRERELEASE "alpha"
#define WORR_BUILD_METADATA "20240315"
#define WORR_SEMVER "0.1.0-alpha+20240315"
