#pragma once

// This file is auto-generated by tools/release/bump_version.py. Do not edit manually.

namespace worr::version {
inline constexpr int kMajor = 0;
inline constexpr int kMinor = 1;
inline constexpr int kPatch = 0;
inline constexpr bool kHasPrerelease = false;
inline constexpr bool kHasBuildMetadata = false;
inline constexpr const char* kPrerelease = "";
inline constexpr const char* kBuildMetadata = "";
inline constexpr const char* kVersion = "0.1.0";
}  // namespace worr::version

